title: Pedro's Lily-Notes
author: Pedro Pessoa
email: pedropsb95@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog intend to provide personal notes about lilypond, that may be structured into tutorials.

# social links
twitter_username: foo-twitter-handle
github_username:  pedro-psb

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
